terminate called after throwing an instance of 'loop_error'
  what():  loop error: statements 0 and 1 cannot be fused together due to negative dependence
Aborted (core dumped)
